### ISSUE TITLE
Text editing

### ISSUE THREAD

**Issue by whit33r** [vitamins/archinstaller#23]
Not the nano comes in text editing but also VI.

**Comment by vitamins** [comment]
Hi,
please check the variable $EDITOR in the terminal where you run archinstaller.
echo $EDITOR
The editor which is set by this variable is used, and if EDITOR is not set, nano is used as a fallback.
This behaviour is documented in README.
I think that on the archiso, EDITOR is set to vi.
EDIT: Yes, i checked the latest archiso and EDITOR is "vi".

**Comment by vitamins** [comment]
Closing, works as intended.
