### ISSUE TITLE
segmentation fault during adduser

### ISSUE THREAD

**Issue by ghost** [vitamins/archinstaller#24]
Hi, during adduser step, it crashed due to segmentation fault. Although, I'm trying to use this on chromebook pixel, so could be due to weird setup. 

Would be nice to have some way of resuming where you left off before.

**Comment by vitamins** [comment]
Hi,
i agree that it would be nice to have some way of resuming where you left off before, but i can not think of a simple way to implement this without having to introduce a lot of additional error checks.
My standpoint is that ideally the script should never be interrupted by segmentation faults or other errors, and that it should be free of such critical bugs, so resuming is not necessary.

Regarding the useradd command, these are the code lines around it:
...
passwd -R /mnt root
useradd -R /mnt -m -g users -s /bin/bash "$user_name"
passwd -R /mnt "$user_name"
...

Please run these commands manually, in the same order, to identify which command has caused the segmentation fault. (Of course you will have to mount the root partition to /mnt beforehand. Also you have to replace "user_name".)
