### ISSUE TITLE
Which hooks and k_modules use on this scenario?

### ISSUE THREAD

**Issue by vonpupp** [vitamins/archinstaller#28]
Hello,

Your installer looks very promising and I just tested it. Unfortunately it didn't work properly, I'm pretty sure it is my mistake! I was working on my own installer very tailored to my needs but when I saw yours I wanted to give it a try.

I setup a repository [1] with some scripts to help me out creating a VM based on the Arch Linux ISO, it is the most automated way I could figure to debug my installer. I wonder what you used and how you create, destroy, start and stop a VM automatically (without Vagrant) to test archinstaller. I hope mine could help you out in case you need them =)

I customized the ari.conf as [2]. I would like to use UEFI, HD encryption and GRUB but since I am quite new to Arch, I'm not sure if I have to modify the hooks or the k_modules to support those features. Could you please help me?

Additionally I could manually partition, LVM and setup LUKS with some basic scripts [3]. I guess that archinstaller does not support LVM on the ari.conf, so it would be possible to use my partitioning script and mount the needed folders before using archinstaller? If so, how?

Thank you very much!

[1] https://github.com/vonpupp/arch-install-vbox-scripts
[2] https://github.com/vonpupp/archinstaller/blob/master/ari.conf
[3] https://github.com/vonpupp/arch-install-scripts/blob/master/libs-01-partitioning/scheme01/all.sh

**Comment by vitamins** [comment]
Hi,
to test the installer i used qemu, and manual testing, no automation.
It is surely possible to use UEFI and GRUB together with this script, just set the relevant options.

> Additionally I could manually partition, LVM and setup LUKS with some basic scripts [3]. I guess that archinstaller does not support LVM on the ari.conf, so it would be possible to use my partitioning script and mount the needed folders before using archinstaller? If so, how?

See https://github.com/vitamins/archinstaller#manual-partitioning
Before running the script, set up LVM and LUKS and mount the partitions. In the config, set the kernel commandline and set the hooks according to the wiki page about LVM and LUKS. I don't think you need to set the kernel modules.

I encourage you to do the installation of arch linux manually with the beginner's guide first. After that you will understand how to set the options. Also read the wiki pages about LVM and LUKS.

**Comment by vonpupp** [comment]
Thank you. Everything is working now =)
